# Generated by Django 2.1.15 on 2022-03-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Pelicula', max_length=50)),
                ('director', models.CharField(default='Director', max_length=50)),
                ('genero', models.CharField(default='Genero', max_length=50)),
                ('duracion', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'peliculas',
            },
        ),
    ]
