# Generated by Django 2.1.15 on 2022-03-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
