# Generated by Django 2.1.15 on 2022-03-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='autor',
            field=models.CharField(default='Autor', max_length=50),
        ),
    ]
