# Generated by Django 2.1.15 on 2022-03-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='plataforma',
            field=models.CharField(default='PC', max_length=50),
        ),
    ]
